name: build and push image to ECR

on:
  push:
    branches:
      - main
permissions: 
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::093984136187:role/github-actions-ecr-role
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=093984136187.dkr.ecr.us-east-1-amazonaws.com/my-app:one
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          
        
          
          
        
        
